### ISSUE TITLE
Notes about compiling and running

### ISSUE THREAD

**Issue by prool** [Seifert69/DikuMUD3#1]
1. Need creating directory 'log' in directory 'vme'

2. In dir vme/lib/ply need create file players.id:

echo 0 > players.id

3. Directory vme/www is root dir of MUD web site

cp mudenter.html index.html

In file index.html replace "localhost" to your FQDN

I did it all and it worked :-)

**Comment by Seifert69** [comment]
1. Odd you needed that. If nothing is specified it should just dump the log
in bin. If you want to add a log location I suggest -l ../log/
2. I added the players.id file in lib/ (not in lib/ply)
3. I renamed mudenter. and I'll add a note about FQDN.

Happy it worked & thanks for the feedback. Drop me a note if there's
anything I didn't catch :)
