### ISSUE TITLE
Default logging is too high

### ISSUE THREAD

**Issue by rgautier** [Seifert69/DikuMUD3#10]
I'd like to recommend that logging be reduced in the version on Github in the default install.
Currently ALL input is logged to vme.log and mplex.log (duplicative).  While this makes sense for debugging, some may decide to use this out of the box.

I'd also recommend that input to the password prompt be specifically turned off in all logging modes for vme.
(This will be much harder to capture in the mplex.log which is unaware of the context).

**Comment by Seifert69** [comment]
I've removed debug logging which shouldn't have been there. Commands no longer in log.
