### ISSUE TITLE
Old Age

### ISSUE THREAD

**Issue by Seifert69** [Seifert69/DikuMUD3#106]
Need to fix (very) old players that login and are dead due to old age.

**Comment by ellpc** [comment]
How are you thinking about 'fixing' them? Do you want to make them live again or just not fully dead?

**Comment by Seifert69** [comment]
We usually just load the char and change it's age... Just ask in game plz.

**Comment by ellpc** [comment]
https://github.com/ellpc/DikuMUD3/tree/fountainofyouth/vme

**Comment by Seifert69** [comment]
Uuuu.... So nice ! Very excited 😄

**Comment by Seifert69** [comment]
Thank you so much :-)
