### ISSUE TITLE
MUD dies after running for hours

### ISSUE THREAD

**Issue by rgautier** [Seifert69/DikuMUD3#11]
Two days in a row now, the MUD process has just ended around 11:45 PM for no particular reason.  No one is logged into it, the vme process just ends (no error logged, no input logged), no process error on stderr.

Last logged events are merely zone file errors that had occurred throughout the day regarding objects missing rooms.

**Comment by prool** [comment]
me too ;)

gdb is founded crashes in lines:

dilrun.cpp:1070
event.cpp:222
event.cpp:227
event.cpp:231

**Comment by rgautier** [comment]
This is the tail of last night's vme.log
--
Fri Jul 24 21:20:49 2020 :: hobgob/Zone Reset Error: No west direction from room hidden_cave in door.
Fri Jul 24 21:20:49 2020 :: hobgob/Reset Error: Don't know where to put pseudo@hobgob
Fri Jul 24 21:20:49 2020 :: hobgob/Reset Error: Don't know where to put lover_2@hobgob
Fri Jul 24 21:20:49 2020 :: hobgob/Reset Error: Don't know where to put kitten@hobgob
Fri Jul 24 21:20:49 2020 :: hobgob/Reset Error: Don't know where to put mikisiw@hobgob
Fri Jul 24 21:23:46 2020 :: sorcerer/Reset Error: Don't know where to put good_mage@sorcerer
Fri Jul 24 21:25:36 2020 :: Kicking out idle player waiting for name.
Fri Jul 24 21:30:36 2020 :: Kicking out idle player waiting for name.
Fri Jul 24 21:31:33 2020 :: assassin/Reset Error: Don't know where to put assassin_guard@assassin
Fri Jul 24 21:35:36 2020 :: Kicking out idle player waiting for name.
Fri Jul 24 21:39:27 2020 :: offices/Reset Error: Don't know where to put shredder@offices
Fri Jul 24 21:39:27 2020 :: offices/Reset Error: Don't know where to put shredder@offices
Fri Jul 24 21:39:41 2020 :: midgaard/Zone Reset Error: No down direction from room wall_rd2 in door.
Fri Jul 24 21:39:41 2020 :: midgaard/Zone Reset Error: No down direction from room wall_rd11 in door.
Fri Jul 24 21:40:36 2020 :: Kicking out idle player waiting for name.
Fri Jul 24 21:40:52 2020 :: halfzon/Reset Error: Don't know where to put lasrarner@halfzon
Fri Jul 24 21:40:52 2020 :: halfzon/Reset Error: Don't know where to put hanook@halfzon
Fri Jul 24 21:40:52 2020 :: halfzon/Reset Error: Don't know where to put pallowaz@halfzon
Fri Jul 24 21:42:01 2020 :: hobgob/Zone Reset Error: No west direction from room hidden_cave in door.
Fri Jul 24 21:42:01 2020 :: hobgob/Reset Error: Don't know where to put pseudo@hobgob
Fri Jul 24 21:42:01 2020 :: hobgob/Reset Error: Don't know where to put lover_2@hobgob
Fri Jul 24 21:42:01 2020 :: hobgob/Reset Error: Don't know where to put kitten@hobgob
Fri Jul 24 21:42:01 2020 :: hobgob/Reset Error: Don't know where to put mikisiw@hobgob
Fri Jul 24 21:45:21 2020 :: sorcerer/Reset Error: Don't know where to put good_mage@sorcerer
Fri Jul 24 21:45:36 2020 :: Kicking out idle player waiting for name.
Fri Jul 24 21:45:52 2020 :: Error: patrol_guard1@midgaard had heartbeat of 1.
Fri Jul 24 21:45:52 2020 :: Error: patrol_guard1@midgaard had heartbeat of 1.
Fri Jul 24 21:45:52 2020 :: DIL heartbeat was

**Comment by rgautier** [comment]
Hrm - just got this:
[1]-  Segmentation fault      nohup ../bin/vme 2> vmeerr.log > nohupvme.log
[3]+  Exit 1                  nohup ../bin/mplex -w -p 4280 2> mplexerr.log > nohupmplex.log

vme.log on attempted restart - 
Sat Jul 25 07:37:27 2020 :: haon_dor/DIL walk_room() unable to locate room throne@dwarves
Sat Jul 25 07:37:27 2020 :: haon_dor/DIL walk_room() unable to locate room throne@dwarves
Sat Jul 25 07:37:36 2020 :: midgaard/DIL watercurrent(): No such direction 1 in room river1@midgaard
Sat Jul 25 07:37:41 2020 :: Booting Eliza
Sat Jul 25 07:37:41 2020 :: Booting Eliza Done.
Sat Jul 25 07:37:51 2020 :: A multi-host has connected to the game.
Sat Jul 25 07:37:51 2020 :: Sending Mudname Valhalla Test Mud, Len 18
Sat Jul 25 07:37:51 2020 :: Sending Default Colors to multihost.
Sat Jul 25 07:39:19 2020 :: goblin_cave/DIL walk_room() unable to locate room pt_d_fo@elfdom
Sat Jul 25 07:39:44 2020 :: goblin_cave/DIL walk_room() unable to locate room fireplac@elfdom

**Comment by Seifert69** [comment]
I'll see if I can figure out what it is. Hang on 24 hours. :)

**Comment by Seifert69** [comment]
Lines numbers dont match up precisely with my code.

What OS'es are you running on?

Can you possibly mail me a backtrace from gdb?

And a few of the key frames?

If it's in the line I think it is, then I'd love to see a print of:

if (((dilprg *)((unit_fptr *)tmp_event->arg2)->data)->fp->tmpl->prgname)


I'm thinking maybe "fp" or "tmpl" might be NULL ?

And just to be sure: You're not compiling zones in the zone/ dir while the
MUD is running, right?

Best, M

**Comment by prool** [comment]
> Lines numbers dont match up precisely with my code.

Maybe, I'm using old version of code.

I'm retesting new MUD code under gdb, wait plz about 24h.

My OS is Ubuntu 18.04.4 x86_64

**Comment by Seifert69** [comment]
Ok.

I'm running for 14 days without issues. Please get the latest. I'm updating
a lot these days

**Comment by rgautier** [comment]
Am running CentOS 7, patched.  No core dumps.. (I might have them turned
off?)

I was asleep when it crashed, so not compiling zones.

**Comment by Seifert69** [comment]
I figured out a neat way to reproduce (remove usleep() delay to accelerate
time by 500x+). The bug is super complicated and will take a while to
resolve.
I think I'll end up having to rewrite a few things to classes to make it
more bullet proof. Will let you know how it goes.
PS. The production MUD can run for 20+ days without issues, it's apparently
only the combo on the scaled back version.

**Comment by rgautier** [comment]
I believe that one thing that made it crash after a time was leaving a
browser connected to it, without it logging in.  The MUD would disconnect
it, over and over.  Last night, I didn't leave my browser open to it, and
it didn't crash...has been up for 36 hours now.

**Comment by Seifert69** [comment]
I can also make it crash without now :-)

I think maybe some of my newer DIL code is triggering very rarely.

I'm running valgrind now, found a small handful of issues that I fixed but
I can still crash it.

Running prolonged now in valgrind (because it slows down the machine).  It
might take a few weeks to figure it out. It's one of those nightmare bugs
:))


Best

**Comment by rgautier** [comment]
So, are you saying you're only releasing the scaled back version?  :)
I definitely know we're missing some zones (all those attempted trips to elfdom by my NPCs).  Have you thought of only including a simple Zone with no actions that tie into missing zones for the release version?

**Comment by Seifert69** [comment]
We released everything except zones special to Valhalla MUD. Those zones
are not really mine to give away :o) If there are some particular zones you
would like to see here, drop me an email and I'll poke Ken and see what he
says. I like your idea though. :o)

**Comment by Seifert69** [comment]
I've located and fixed the bug - which by the way was extremely hard :-)
The issue happened if a run_dil() had recursively called itself, then there
was a risk that it would free the dilprg struct twice.

Also ran everything through valgrind and caught surprisingly few additional
errors.

Will upload sources soon.

**Comment by rgautier** [comment]
Pulled a fresh and running now - will let you know if it dies in the next 48 hours for no reason.
But I do see you've done a lot of zone cleanup work...nice job!

**Comment by rgautier** [comment]
Crashed at about 1PM today.  No one was logged into it.
tail of vme.log is below - doesn't look like a nesting issue....

Is there anything I can do to get to the bottom of this?  (I'm open to trying anything you need to help debug it)

Wed Jul 29 12:45:24 2020 :: run_dil() do_say has nest 2
Wed Jul 29 12:45:57 2020 :: run_dil() officerprg has nest 2
Wed Jul 29 12:46:35 2020 :: patrol guard was given  2 copper pieces by DIL guard3@midwalls.
Wed Jul 29 12:46:37 2020 :: run_dil() do_say has nest 2
Wed Jul 29 12:46:37 2020 :: run_dil() pain_dil has nest 2
Wed Jul 29 12:47:29 2020 :: run_dil() do_say has nest 2
Wed Jul 29 12:47:29 2020 :: run_dil() pain_dil has nest 2
Wed Jul 29 12:48:22 2020 :: gate guard was given  2 copper pieces by DIL gate_n1@midwalls.
Wed Jul 29 12:48:26 2020 :: patrol guard was given  2 copper pieces by DIL guard8@midwalls.
Wed Jul 29 12:49:04 2020 :: run_dil() do_say has nest 2
Wed Jul 29 12:49:04 2020 :: run_dil() pain_dil has nest 2
Wed Jul 29 12:49:21 2020 :: run_dil() do_say has nest 2
Wed Jul 29 12:51:06 2020 :: gate guard was given  2 copper pieces by DIL gate_e2@midwalls.
Wed Jul 29 12:51:19 2020 :: offices/Reset Error: Don't know where to put shredder@offices
Wed Jul 29 12:51:19 2020 :: offices/Reset Error: Don't know where to put shredder@offices
Wed Jul 29 12:51:26 2020 :: patrol guard was given  2 copper pieces by DIL guard11@midwalls.
Wed Jul 29 12:52:20 2020 :: run_dil() do_say has nest 2
Wed Jul 29 12:52:20 2020 :: run_dil() pain_dil has nest 2
Wed Jul 29 12:55:53 2020 :: patrol guard was given  2 copper pieces by DIL guard7@midwalls.
Wed Jul 29 12:56:45 2020 :: halfzon/Reset Error: Don't know where to put lasrarner@halfzon
Wed Jul 29 12:56:45 2020 :: halfzon/Reset Error: Don't know where to put hanook@halfzon
Wed Jul 29 12:56:45 2020 :: halfzon/Reset Error: Don't know where to put pallowaz@halfzon
Wed Jul 29 12:56:50 2020 :: run_dil() do_say has nest 2
Wed Jul 29 12:56:50 2020 :: run_dil() pain_dil has nest 2
Wed Jul 29 12:57:11 2020 :: kingc/Reset Error: Don't know where to put pool_monster@kingc

**Comment by Seifert69** [comment]
Oh no. :-( I'll look into it again :-)

**Comment by Seifert69** [comment]
No luck yet in reproducing it. Can you double check you're running on the
new version. If you can run the server from gdb and let me know how it
terminates, either the stacktrace or the exit code please. Please do pull
the latest source as I differentiated the exit codes (they all tended to
exit with 1 and were undistinguishable)
. Thanks :)

**Comment by rgautier** [comment]
I had pulled and 'make clean' / 'make all' before running last night.  The issue with running from gdb is I'm disconnecting from my cloud server - so to keep it running, I'm running in nohup and background... Not sure how to interactively run in gdb and then disconnect/background the task.

Suggestions?

**Comment by Seifert69** [comment]
Hi Rich,

Thank you. I can't make mine "crash" in any way. However, if I run it for
21 day, it will get killed by Linux for using too much memory.

I can see there's a memory leak related to DIL. I'll start working on that
but it'll take a few weeks I suspect. My plan is to change the
diltemplate and dilframe structs to classes, to maintain counters, and
thereby figure out where the memory is lost.

If you look in:

less /var/log/kern.log

You might be able to see if Linux killed your vme process.

Best, Michael

**Comment by prool** [comment]
I confirm the leak.
Look at the graph
http://prooltest-4g.kharkov.org/munin/localdomain/localhost.localdomain/memory.html
Leak from 9:00 Wed to current time.
Towers is the Minecraft game of my grandson ;-)

**Comment by Seifert69** [comment]
Thank you. Think I found it but it'll take a little while to fix. Not as
simple as tracking with classes. There's some really odd code around
dilframe handling and reallocate.

**Comment by Seifert69** [comment]
If you have the time please try to pull and run again.

There's still a leak, looks like it's in DIL variables. But I suspect you
can run for long now without running out of resources.

I'll look at it but this time it'll take a few weeks unless it still goes
down after 11 hours :)))

**Comment by rgautier** [comment]
Cannot compile on new pull:

g++ -I. -I.. -I vmc -DVMC  -DLINUX -DPOSIX -pipe -m64 -std=c++11 -DMUD_DEBUG -g                                                   -Wall   -O0 ../../build//vmc/vmc.o ../../build//vmc/vmc_process.o ../../build//v                                                  mc/utility.o ../../build//vmc/structs.o ../../build//vmc/destruct.o ../../build/                                                  /vmc/spec_assign.o ../../build//vmc/money.o ../../build//vmc/pp1.o ../../build//                                                  vmc/pp2.o ../../build//vmc/pp3.o ../../build//vmc/pp4.o ../../build//vmc/pp5.o .                                                  ./../build//vmc/pp6.o ../../build//vmc/pp7.o ../../build//vmc/pp8.o ../../build/                                                  /vmc/vmc_db_file.o ../../build//vmc/tmp_vmcpar.o ../../build//vmc/tmp_vmclex.o .                                                  ./../build//vmc/tmp_dilpar.o ../../build//vmc/tmp_dillex.o ../../build//color.o                                                   ../../build//textutil.o ../../build//namelist.o ../../build//files.o ../../build                                                  //extra.o ../../build//bytestring.o ../../build//common.o ../../build//intlist.o                                                   ../../build//dilshare.o -lfl -g -o ../../bin/vmc
../../build//dilshare.o: In function `dilprg::dilprg(unit_data*, int)':
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:79: undefined reference to `                                                  g_nDilPrg'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:79: undefined reference to `                                                  g_nDilPrg'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:84: undefined reference to `                                                  dil_list'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:85: undefined reference to `                                                  dil_list'
../../build//dilshare.o: In function `dilprg::~dilprg()':
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:130: undefined reference to                                                   `g_nDilPrg'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:130: undefined reference to                                                   `g_nDilPrg'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:132: undefined reference to                                                   `dil_list'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:134: undefined reference to                                                   `dil_list'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:136: undefined reference to                                                   `dil_list_nextdude'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:136: undefined reference to                                                   `dil_list'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:137: undefined reference to                                                   `dil_list_nextdude'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:138: undefined reference to                                                   `dil_list'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:143: undefined reference to                                                   `dil_list'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:147: undefined reference to                                                   `dil_list_nextdude'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:148: undefined reference to                                                   `dil_list_nextdude'
/home/rgautier/foxmud/DikuMUD3/vme/src/dilshare.cpp:175: undefined reference to                                                   `dil_free_template(diltemplate*, int)'

**Comment by Seifert69** [comment]
Blast it, I keep forgetting the Makefile, sorry. It's up now :)

**Comment by Seifert69** [comment]
So I found the memory leak. stack.init(10) apparently was the culprit. I've
never seen that class before.

Anyway there seems to be one pesky, elusive bug I'm still hunting for. I'll
let you know when I've fixed it, then it should be all good.

Best,

**Comment by Seifert69** [comment]
I've begun some very low level memory debugging. In that process ive
emplaced the dilprg class. As soon as I did that the server stayed up for
101 days until I stopped it. And zero memory leakage.

Bad news is of course that there's still an unfound mem over run.

I'll keep  at it :)

**Comment by rgautier** [comment]
Can you push the new dilprg class?  I pulled the one yesterday, but still had an issue.  One interesting thing to mention is I'm running in a VPS environment with a 512MB limit.  Looking at my history, it looks like I'm hitting memory limits.

Unrelated to your bug, but part of my problem in giving you more data:
On the downside, I'm no CentOS expert, but that's the image I'm stuck on, and I STILL can't figure out why I'm not getting core dumps.  I've tried removing aprt and still can't get permissions to modify kernel.core_pattern.  While my hard limit is 'unlimited' and I've tried setting the soft limit, it constantly resets to 0, and my core_pattern STILL wants to send dumps to the not-installed aprt.  Tried installing aprt again to see if I could get it to actually do something...no cores...

So I have to catch it crashing live...with it being unpredictable (12 hours? 36?) I'm not having any luck doing that.

**Comment by Seifert69** [comment]
Finally found the bug(s). Please pull and try again. I'm quite confident
this was it. I ran it super stable for 220 days with no issues and no
memory increase.

The GitHUB distro uses 26MB of memory as far as I recall, now that its been
fixed. Before it would just keep climbing until it got zapped by your OS.

I have the same core dump gripes as you on Ubuntu and on our production
Ubuntu as well

Let me know how it goes. I'd love to hear about your project someday.

Best, Michael

**Comment by rgautier** [comment]
Pulled and rebuilt now - will leave it up and see how it goes.  

For reference tomorrow morning:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
22553 rgautier  20   0   56160   2108   1512 R   0.0  0.4   0:00.09 top
22518 rgautier  20   0  135192   3348   2800 S   0.0  0.6   0:00.00 ../bin/mplex -w -p 4280
22502 rgautier  20   0  159128  29660   3176 S   0.3  5.7   0:01.02 ../bin/vme

**Comment by Seifert69** [comment]
Great. Found a few places where I had been too strict, so you may crash it
with certain player actions. But it's fixed and you can pull it whenever
you want.

**Comment by rgautier** [comment]
Overnight comparison. Holding steady at 159128 virtual memory overnight. No unusual memory growth.

22974 root      20   0 1029244  41160  29668 S   0.0  7.9   1:23.27 /usr/bin/python2 -s /usr/bin/fail2ban-server -xf start
22518 rgautier  20   0  135192   3364   2816 S   0.0  0.6   0:00.60 ../bin/mplex -w -p 4280
22502 rgautier  20   0  159128  31380   3188 S   0.4  6.0   1:51.44 ../bin/vme

I think you can close the issue 👍

**Comment by Seifert69** [comment]
I've added a new wiz command "wtimewarp" (w for wiz). You can specify for
how many seconds of ticks the game will accelerate.

E.g. wtimewarp 3600 will make vme run at top speed, and what would normally
have taken an hour to pass, happens in a few seconds.  You can't log in
while this is going on. Could be fixed but I didn't bother since it's a
debugging function.  So now you can simulate the server being up for 36
hours easily rather than having to wait 36 hours.

--Michael
