### ISSUE TITLE
Compiling Issue...destruct.cpp

### ISSUE THREAD

**Issue by rgautier** [Seifert69/DikuMUD3#12]
This is a weird one - to me it looks like it's trying to include the warning that it's error-ing on - but Makefile includes that flag.

g++  -I.  -I.. -DVMC_SRC -DVMC  -DLINUX -DPOSIX -pipe -m64 -DMUD_DEBUG -g -Wall  -g -c destruct.cpp -o ../../build//vmc/destruct.o
In file included from /usr/include/c++/4.8.2/type_traits:35:0,
                 from ../destruct.cpp:12,
                 from destruct.cpp:11:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^

**Comment by rgautier** [comment]
Added -std=c++11 to Makefile.ubuntu in vmc directory to get past this...

**Comment by Seifert69** [comment]
Sorry, forgot to upload my make.

**Comment by Seifert69** [comment]
Makefile pushed.
