### ISSUE TITLE
telnet & change terminal

### ISSUE THREAD

**Issue by Seifert69** [Seifert69/DikuMUD3#137]
Seido says 'ah, I have done 'change terminal' and disconnected, after that I could not log-in with telnet. I logged in with web client, changed option back, and only after that can connect with my client'

**Comment by Seifert69** [comment]
Unable to reproduce.

**Comment by konelav** [comment]
Sorry I gave incorrect decription; I meant `change telnet`, of course, and it is easily reproducable with clean registration, just checked.
Step-by-step:
- `$ telnet valhalla.com 4242`;
- register new character (at this time I took dwarf-fighter-neutral, most certainly it does not matters);
- `save`;
- `change telnet`;
- ^]  + `quit`;
- `$ telnet valhalla.com 4242`
- enter login, password => "Wrong password".

**Comment by Seifert69** [comment]
Thanks I'll check it out.

Is there anything achievable by 'change telnet' (other than breaking the
pwd :))
