### ISSUE TITLE
No leveling

### ISSUE THREAD

**Issue by prool** [Seifert69/DikuMUD3#14]
Hi!

I went to the western forest to hunt some rabbits and fox

And see no level up:

score

Prool the human (Neutral). You have 1428 experience points and you need -28 to the next level. You have 41(41) hit, 103(103) mana, 211(211) endurance points. You are a protected citizen.You are standing.

**Comment by rgautier** [comment]
Have you tried 'level gain'?

**Comment by prool** [comment]
level gain worked! Thank You!

**Comment by Seifert69** [comment]
It was a super fair question. I added a help line to score when you're
ready to raise a level and a help line to level to make you aware you need
to practice your skills and abilities :-)

**Comment by Seifert69** [comment]
BTW, go to the Chicken's Rest Inn in Udgaard to train. There are 4
beginner's teachers there. Later you can find your guild teachers.

I'm planning on adding remote training for newbies so you can practice from
anywhere without the hassle of finding your teachers.

Best, Michael
