### ISSUE TITLE
Udgaard shopkeepers not restocking inventory

### ISSUE THREAD

**Issue by chrisspanton** [Seifert69/DikuMUD3#142]
Should restock in time, currently requires murder.

**Comment by Seifert69** [comment]
Do you know if this was fixed?

**Comment by danielw97** [comment]
Just chiming in here several years later to say that I'm able to reproduce this on my local copy running on Debian 12.
Shops aren't restocked after a zone reset, unless there's something else that triggers this? I'm still getting to grips with how the engine works although is there something I can do to narrow down this issue?

**Comment by danielw97** [comment]
Slightly off-topic for this repo, although I am able to observe this behavior with Diku2 which as I understand it isn't being actively worked on although wanted to notify you.

**Comment by Seifert69** [comment]
Sounds like the shopkeepers are running on their own timer, which makes sense.

**Comment by Seifert69** [comment]
So closing this issue.
