### ISSUE TITLE
Falling while climbing up results in moving up

### ISSUE THREAD

**Issue by chrisspanton** [Seifert69/DikuMUD3#143]
Should result in failing to move up, I suspect. Who falls up?

**Comment by Seifert69** [comment]
The EX_FALL_THIS_WAY (I think it is called) should be set properly. I'll look

**Comment by chrisspanton** [comment]
Here's a sample of a climb set on a room that results in falling up (from trail_02@gremlin):

up open {EX_CLIMB, EX_FALL_THIS_WAY} difficulty 0 to outcropping;

I could see how that may result in falling up, I guess? Seems like fall should always be down, however. No?

**Comment by Seifert69** [comment]
Yes that means if you fail your climb check, the you will fall "up", i.e. move to the next room in the up direction.

If you want to "stay put" then remove the EX_FALL_THIS_WAY flag.

If you want to "fall down" and move to the room in the down direction, then remove the flag, and add the flag to the down exit

**Comment by Seifert69** [comment]
Seems like it's expected behavior.
