### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by prool** [Seifert69/DikuMUD3#15]
Hello!

I'm download current version DikuMUD3, compile it and run.

Connect, create character, enter 'save' command and disconnect (control D in tintin++)

And try reconnect and have crash after write password:

gdb says:

Thread 1 "vme" received signal SIGSEGV, Segmentation fault.
0x0000555555592dbc in connect_game (pc=0x555555f6f500) at nanny.cpp:198
198         CHAR_DESCRIPTOR(pc)->logon = time(0);
(gdb) bt
#0  0x0000555555592dbc in connect_game (pc=0x555555f6f500) at nanny.cpp:198
#1  0x0000555555593222 in enter_game (ch=0x555555f6f500, dilway=1) at nanny.cpp:304
#2  0x0000555555593d23 in nanny_motd (d=0x555555bcaea0, arg=0x7fffffffd807 "") at nanny.cpp:457
#3  0x0000555555593c62 in set_descriptor_fptr (d=0x555555bcaea0, fptr=0x555555593caf <nanny_motd(descriptor_data*, char*)>, 
    call=1 '\001') at nanny.cpp:408
#4  0x0000555555595422 in nanny_existing_pwd (d=0x555555bcaea0, arg=0x555556c0af70 "paroll666") at nanny.cpp:899
#5  0x000055555559973e in game_event () at main.cpp:436
#6  0x00005555555992dc in game_loop () at main.cpp:338
#7  0x0000555555599225 in run_the_game (srvcfg=0x7fffffffdc50 "../etc/server.cfg") at main.cpp:295
#8  0x000055555559901e in main (argc=1, argv=0x7fffffffdf48) at main.cpp:238
(gdb) 

With best regards, Serge "Prool" Pustovoitoff

**Comment by Seifert69** [comment]
I'll get it fixed soon and will let you know.

Please be aware that your password is visible in the backtrace below. But
thanks for including it, tremendously helpful as my server reacts slightly
differently.

**Comment by prool** [comment]
I hurried and my password burned out  :-)

**Comment by Seifert69** [comment]
Thanks Serge, a bug in one of my changes. It's fixed now, please pull and
compile.
