### ISSUE TITLE
Unable to advance character with 'advance' command.

### ISSUE THREAD

**Issue by rgautier** [Seifert69/DikuMUD3#16]
102m/164e/35h>
advance Fullpint admin 254
That character is not here.

102m/164e/35h>
look fullpint
He has big green ears, and long greasy hair.
Fullpint is a protected citizen.
<wielded> | a short sword
<worn as shield> | a small wooden shield
<worn around neck> | Odin's Medallion of Guild Transport
<worn on body> | a leather jerkin
<worn about body> | a dark cloak
<worn across chest> | the Broach of Thieving
<worn on legs> | a pair of leather pants
<worn on feet> | a pair of leather boots

**Comment by Seifert69** [comment]
Try to reverse

Advance admin full pint 254

**Comment by rgautier** [comment]
Corrected Wiki - advance command worked.
Also noted that character must be present.
