### ISSUE TITLE
Compilation Issues(CentOS 7):

### ISSUE THREAD

**Issue by slowlane81** [Seifert69/DikuMUD3#198]
I looked at several clsoed errors like the one that I had(repeatedly)

g++  -I.  -I.. -DVMC_SRC -DVMC  -DLINUX -DPOSIX -pipe -DMUD_DEBUG -g -Wall  -g -c dilshare.cpp -o ../../build//vmc/dilshare.o
In file included from /usr/include/c++/4.8.2/forward_list:35:0,
                 from ../structs.h:10,
                 from ../utility.cpp:14,
                 from utility.cpp:10:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8.2/forward_list:35:0,
                 from ../structs.h:10,
                 from ../structs.cpp:8,
                 from structs.cpp:11:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^

My makefile already has -std=c++11 in it, what else could be causing this issue?

**Comment by Seifert69** [comment]
That's perplexing. I did some searching - with no luck. When I look at your error, it's not obvious that the -std=c++11 flag is set:

g++ -I. -I.. -DVMC_SRC -DVMC -DLINUX -DPOSIX -pipe -DMUD_DEBUG -g -Wall -g -c dilshare.cpp -o ../../build//vmc/dilshare.o

Could you perhaps try to compile with just that line and add the two flags by hand, see what happens, i.e. something like:

g++ -I. -I.. -DVMC_SRC -DVMC -DLINUX -DPOSIX -pipe -DMUD_DEBUG -g -Wall -g **-std=c++11**  -c dilshare.cpp -o ../../build//vmc/dilshare.o

You could also try with the std=gnu++11

Let me know how it goes please.

**Comment by slowlane81** [comment]
It leaves this error when I add the flags by hand:

Assembler messages:
Fatal error: can't create ../../build//vmc/dilshare.o: No such file or directory

**Comment by Seifert69** [comment]
If you're up for it you might want to try to build with the new CMake that was just added today. Would love to hear how that works out.

**Comment by bluedreamer** [comment]
I started to test this on cent 7, got distracted with xmas, you need to install cmake3 though from epel and maybe downgrade the minimum version in the top level CMakeLists.txt - I think the most "advanced" feature Im using is from 3.12

**Comment by Seifert69** [comment]
So sudo apt install cmake3 ?

**Comment by bluedreamer** [comment]
Been a while since I've used ubuntu/debian. A lot of distro's are shipping with cmake 3 by default - you can check with the usual `cmake --version`

Which version are you using? I can install a VM then and test it out

**Comment by Seifert69** [comment]
My version was too old. Thanks

**Comment by Seifert69** [comment]
Thank you @bluedreamer :-)
