### ISSUE TITLE
Compilation error due to instantiation of undefined template

### ISSUE THREAD

**Issue by luciensadi** [Seifert69/DikuMUD3#2]
I ran into this issue while trying to compile the MUD on OS X. Including `<memory>` did not resolve it. Any suggestions or advice would be appreciated.

```
In file included from mplex2/echo_server.cpp:1:
In file included from mplex2/websocketpp/common/memory.hpp:55:
In file included from /usr/local/include/boost/shared_ptr.hpp:17:
In file included from /usr/local/include/boost/smart_ptr/shared_ptr.hpp:23:
In file included from /usr/local/include/boost/config/no_tr1/memory.hpp:21:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:652:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:1624:38: error: implicit instantiation of undefined template 'std::__1::owner_less<boost::weak_ptr<void> >'
    : public integral_constant<bool, __is_empty(_Tp)> {};
                                     ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/map:496:18: note: in instantiation of template class 'std::__1::is_empty<std::__1::owner_less<boost::weak_ptr<void> > >' requested here
          bool = is_empty<_Compare>::value && !__libcpp_is_final<_Compare>::value>
                 ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/map:930:13: note: in instantiation of default argument for '__map_value_compare<boost::weak_ptr<void>,
      std::__1::__value_type<boost::weak_ptr<void>, cConHook *>, std::__1::owner_less<boost::weak_ptr<void> > >' required here
    typedef __map_value_compare<key_type, __value_type, key_compare> __vc;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mplex2/echo_server.cpp:21:98: note: in instantiation of template class 'std::__1::map<boost::weak_ptr<void>, cConHook *, std::__1::owner_less<boost::weak_ptr<void> >, std::__1::allocator<std::__1::pair<const
      boost::weak_ptr<void>, cConHook *> > >' requested here
std::map<websocketpp::connection_hdl, cConHook *, std::owner_less<websocketpp::connection_hdl> > g_cMapHandler;
                                                                                                 ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:5282:29: note: template is declared here
template <class _Tp> struct owner_less;
                            ^
1 error generated.
make: *** [../build/./mplex2/echo_server.o] Error 1
```

**Comment by Seifert69** [comment]
I received this note from another user


I was building on CentOS. After installing boost and flex libs I had a
minor problem with the g++ version I was using, just a minor syntax issue
that should be a warning instead of an error. The syntax was just some
whitespace between > on nested templates, but when it popped up in VMC as
well I switched to adding a flag to g++ for different standards version, so
both approaches worked if anyone has that problem later. Only other issue
was I had low mem on virtual server and no swap file, it failed due to low
mem and after that I thought there was a flex/bison issue but a make clean
fixed it so seems it's just a little tempermental if the build isn't clean

**Comment by luciensadi** [comment]
I don't think that's the same issue; I was able to get past the stacked angle brackets problem that user described, and I'm building this on a machine with 16GB RAM and 300GB free drive space that can be consumed by swap.

**Comment by Seifert69** [comment]
The error comes from the only piece of code I've imported to do websockets.
It's from this repo:

https://github.com/zaphoyd/websocketpp

I believe I'm on the latest. Maybe you can poke around there and see if
there's a solution. I can't reproduce on Linux.

Hope you can figure it out. LMK.

**Comment by iamnove** [comment]
Agree that looks like a separate issue local to OS X. Would be nice to see it working on OS X to allow builders to test zones locally (maybe even packaged at some point) so interested if you find a fix. Could raise an issue with that repo. Also boost on brew looks to be a much later version than rh7, not sure what ver Seifert69 is on.

**Comment by Seifert69** [comment]
I can't help with Mac. I purposely dont own Apple products.
Dropme an email on boost please and I'll look into it (I didn't install
Boost, the Perry brothers did)

**Comment by luciensadi** [comment]
This command should output your Boost version at the bottom:

`echo -e '#include <boost/version.hpp>\nBOOST_LIB_VERSION' | gcc -x c++ -E  -`

Mine is `"1_72"`

**Comment by Seifert69** [comment]
Looks like I'm on 1_71. Not too bad ;) Mail me at seifert at dikumud.com
pls.
