### ISSUE TITLE
WebClient Broken on Chrome

### ISSUE THREAD

**Issue by Fizzie68** [Seifert69/DikuMUD3#20]
I have installed the latest upgrades to the web client.  When I try to connect to an existing character (in this case my admin) using Chrome,  it tells me that my password is wrong and disconnects me.   It appears to work fine using FIrefox and Microsoft browsers though.

**Comment by Fizzie68** [comment]
Seems to be working after all.  NOt sure what my initial

**Comment by Seifert69** [comment]
Odd. Maybe caps . Happens to me too :-D (not this particular one)

**Comment by Fizzie68** [comment]
It isn't caps.  I can log in with Firefox and Microsoft edge.  Just not
Chrome. If you cannot duplicate it, I guess I will consider it a problem on
my end. I had thought it was working, but I was using and old version of
client-a.html

Dave

**Comment by Seifert69** [comment]
That's probably it. I did change the HTML files. Please LMK if it comes
back.

**Comment by prool** [comment]
Hello!

My hypothesis: PasswordOn/PasswordOff programs is hurting.

I observed this kind of problem in tintin++ client.

Look please at the file vme.log

Garbage characters '?' appear in front of the password.

**Comment by Seifert69** [comment]
Wait I think I saw the ? And fixed it a while ago.

Have you pulled and compiled everything?

**Comment by prool** [comment]
Solved:

flag -t in mplex avoid the problem

running mplex -p 4242 --- have problem with console MUD client tintin++

if running mplex -t -p 4242 -- it's okay

**Comment by Seifert69** [comment]
Ah yes. I think -c also might solve it. That's ansi mode AFAIR.

Do you know if anyone realistically might use a terminal? Maybe I should
deprecate the TTY support.i don't even know if it's working.

**Comment by prool** [comment]
I think it is difficult to maintain and testing both protocols.

IMHO need to stop supporting the terminal clients.

**Comment by Fizzie68** [comment]
In the case of my original problem with Chrome.  I cleared my browser cache and everything started working just fine.

**Comment by Seifert69** [comment]
I'm closing this issue. LMK if there's anything so it needs to reopen.
