### ISSUE TITLE
Reflective XSS in client-a.html

### ISSUE THREAD

**Issue by rgautier** [Seifert69/DikuMUD3#22]
The parameters can be abused to execute arbitrary JavaScript on the page in the trust of the website.  Must clean parameters.
(client-a.html)

Credit: Simp Von Cuck - Defcon 28

**Comment by rgautier** [comment]
window.onload = function () {
                const urlParams = new URLSearchParams(window.location.search);
                var strConn = encodeURI(urlParams.get('protocol')) + "://" + encodeURI(urlParams.get('host')) + ":" + encodeURI(urlParams.get('port')) + encodeURI(urlParams.get('endpoint'));
                outputText("Accessible MUD client<br/>", false);
                outputText("ESC - clear/focus input field<br/>", false);
                outputText("Up arrow - Scroll back through last commands<br/>", false);
                outputText("Down arrow - Scroll forward through commands<br/>", false);
                outputText("Click map - Pop up map window<br/>", false);
                outputText("Double click main - Pop up fixed main (for easy copy & paste)<br/>", false);
                outputText("Alias, triggers and variables - use commands on MUD server<br/>", false);

                openWSConnection(encodeURI(urlParams.get('protocol')), encodeURI(urlParams.get('host')), encodeURI(urlParams.get('port')), encodeURI(urlParams.get('endpoint')));

**Comment by Fizzie68** [comment]
You also need to encode the next line as well:
`  if (encodeURI(urlParams.get('reader')) != 'true')
`

**Comment by Seifert69** [comment]
Ouch, thank you :-) It's fixed and uploaded.
