### ISSUE TITLE
Missing dependencies in dockerfile

### ISSUE THREAD

**Issue by ocelik111** [Seifert69/DikuMUD3#356]
Hello, I was running through the quickstart guide and the docker build was not completing, I noticed in the dockerfile some dependencies were missing (`libssl-dev` and `rapidjson-dev`) and added them to line 6. Running with the added dependencies completed the build.

```RUN apt-get update && apt-get install -y build-essential ccache bison flex libboost-all-dev libssl-dev rapidjson-dev cmake```

**Comment by Seifert69** [comment]
If you have the time to do a pull request I'd be very grateful :-)  If not, I'll get around to it. Thanks!

**Comment by ocelik111** [comment]
https://github.com/Seifert69/DikuMUD3/pull/357 here ya go chief
