### ISSUE TITLE
DIL - Color object

### ISSUE THREAD

**Issue by Seifert69** [Seifert69/DikuMUD3#44]
Fix the colour_object@basis so that it generates HTML colored titles

**Comment by chrisspanton** [comment]
This is a bit deeper of an issue - currently HTML tags on titles dont render, whether the object generates them appropriately or not. :)

**Comment by Seifert69** [comment]
I just tested it out. I can certainly set the color in any title in a zone
file. E:g.

title "the <div class=cpy>yellow</div> cityguard"

If you're doing it from within the MUD command line itself it's not
possible due to escaping of characters. So if you type <div> it becomes
&lt;div&gt; but of course displays as <div> when you see it in the browser.

Or maybe it's an issue I don't know how to reproduce :)

**Comment by chrisspanton** [comment]
Ah, my issue was definitely in trying to set through the command line. Will work on the object as a workaround.

**Comment by Seifert69** [comment]
Great! That's exactly why we need the object :-)

**Comment by chrisspanton** [comment]
Fixed with PR #98.
