### ISSUE TITLE
DIL - Convert remaining justice.cpp functions to DIL

### ISSUE THREAD

**Issue by Seifert69** [Seifert69/DikuMUD3#45]
Whistle and Protect Lawful have been converted (justice.zon). 

The remaining functions probably need a revision. Perhaps adding an extra $crime or other means might work better.

**Comment by Fizzie68** [comment]
Finishing up work on activate_accuse() and set_witness.  Looking at reward_board and accuse next.  Not sure what the best way to deal with the global crime_list.

**Comment by Seifert69** [comment]
Ok I think I know what might be best (performance) wise. 

Working with a DIL file will like mean you'll have to load it every time it's used and you'll need to do string ops like .split and looping. 

Alternately, if we store it on e.g. the extra description of a global item, or a maybe an accuse board, then we can do it more efficiently.

For example, let's say you want to save a murder crime committed by NPC skaven, then on the global board you can add an extra like this: 

  name: "$crime_skaven_NPC" and possibly set crime type in the int array. In the description you could have a description of the crime: "Skaven murdered xxx in <room name> on <mud date> "

So the neat part is that when you want to search for a crime (when someone uses the accuse command) you simply search for the extra. MIght do it twice, one for PC, one for NPC. Speed is not an issue because the search is running in C.

You might want one list of committed crimes (it's happened but no accuse) and one list of solved crimes (it has been reported by a witness). You could solve that using different prefixed for the same extra list. 

This also has the benefit that it's a lot easier to debug :-) because we can wstat <item> extra
---
I think the key decision is if crimes should be local to a city & a city board? I think that makes sense. In that case, you'd store the crimes on the accuse board in the city.
---

**Comment by Seifert69** [comment]
You of course also need to add a time to the extra items so that we can expire them. Maybe have a piece of code that runs once per hour to clean up old extras with a loop.

**Comment by Fizzie68** [comment]
Did you mean to close this issue?

**Comment by Seifert69** [comment]
Nope :-) did I close it? I suppose we close it when it has been fully
converted

**Comment by Fizzie68** [comment]
I have finished set_witness and activate_ accuse and I am moving on to add_crime.  I will try to use the extra description ideas that you provided.  It sounds better than using files.  I also added playerid into the VMC to get find_player_id, however, if after I am done with the re-write I no longer need the player idx I will not submit that change.

**Comment by Seifert69** [comment]
Sounds fantastic. Shoot me any questions you have or help you need :-)

**Comment by Fizzie68** [comment]
I have a mostly DIL justice system working on my test mud.  I have not converted log_crime(), new_crime_serial_no(), or call_guards() to DIL.  set_witness@justice is activated from log_crime() as is add_crime@justice.  When a person commits a crime it is recorded as an extra on the reward board (this replaces the global crime list). I have also built a timer that will expire the crime extras on the reward_board after an hour. activate_accuse@justice is working so NPCs who witness a crime will go to the Captain and accuse the criminal.  set_witness@justice will apply a $witness extra to the PC or NPC that was present for the crime.  I have also built a timer that gets applied to the PC or NPC that will expire the witness extra after about an hour. After a player or NPC accuses a criminal it will update the players crime stats and if necessary will set a $reward extra on the criminal.  The reward_board will display a list of players Wanted Dead (rewards), Wanted Alive, and Wanted Dead or Alive. It will also display the recent crimes, victims and who accused them.     When a person is wanted Alive, the guards will arrest them and toss them in jail.  I have done testing, but may have some tunnel vision.  I have killed a lot of janitors.

**Comment by Seifert69** [comment]
That sounds fantastic. Like a great improvement to the old system too.

And so nice to get rid of the custom data structures and files on disk.

And finally now possible to debug and manage by imma from within the game.

Thank you!!

Looking forward to the commit and helping to test it out.

It would be great if you could do a little doc on the wiki about where you
place extras and what data the extras contain.  Will make it easier for me
to debug and test out :-))

**Comment by Fizzie68** [comment]
FYI:  

Committed crimes are stored on the reward_board@udgaard in the extras.  Each crim looks like this:
Names
{"$suspect_160","**$crime_Moe_7_janitor_8_5_1**","$SUSPECT"}

There are three names in each entry.  The important one is the second name,  It is $crime_<name of criminal>_<pid of criminal>_<name of victim>_<crime_type>_t<expiration ticks?>_<reported>

"
Moe has been accused in the murder of janitor. This crime was witnessed by: Mr Catherfield.
This crime was also confirmed by Fizban.
"
The descr  for each crime is what is displayed on the reward_board under "Suspects" heading.

Witnesses are also stored in character extras.  THey look like this:
Names
{"$witness","**$witness_161_8_5_1**"}

The important name is the second name:  $witness_<crime_number>_<crime_type>_<pid>_<ticks until witness extra expires>
"
Larry committed a crime.
"
The descr filed for witness is not used at the moment.

Rewards are also stored as an extra on the criminal.  Here is what they look like:

Names
{"$reward","**$reward_250000_1050_1**"}

The second name is the important one:  "$reward_<gold reward>_<xp reward>_<reward increment>

"
A reward of 250000 gold has been offered for the head of Tank
"
the descr of a reward is displayed on the Reward Board under Wanted Dead

**Comment by Seifert69** [comment]
Accomplished by @Fizzie68 :+1:
