### ISSUE TITLE
DIL - Player corpse rotting

### ISSUE THREAD

**Issue by chrisspanton** [Seifert69/DikuMUD3#46]
It appears that player corpses rot in 15-20 minutes. Previously, they would rot in something like 1.5 days.

corpse rotting dil is in death.zon - rot_corpse (). I havent had a chance to look at whether its something there, or something more fundamental in time.

**Comment by chrisspanton** [comment]
This is either not fixed, or re-broken. Corpses are rotting on the production mud in just a few minutes.

**Comment by Seifert69** [comment]
Tested on my local machine and TEST and both work fine. I can see prod is not. I'm trying to figure it out :)
