### ISSUE TITLE
C Bug - Light

### ISSUE THREAD

**Issue by Seifert69** [Seifert69/DikuMUD3#48]
Light, Bright, Illum has a bug. Has been there for ages since 1990s. Somehow it's possible to cause the light values to become incorrect. Right now there is no repro-scenario. So first step would be to reproduce the issue. This issue is quite similar to the weight bug issue

**Comment by chrisspanton** [comment]
Looks like bright is an sbit8, when you overflow it loops around. Reproduce by cast spell sun globe (generates bright +3 on an object) and drop globe until you get to 128, will loop around and make the room dark. 

Suggest using sbit32 for bright values to address. I’m not super familiar with the CPP source files. Happy to try and hack the change in, but might be easier if you’re familiar?

**Comment by chrisspanton** [comment]
Loops around to -126 or so. See room brightness with wstat room.

**Comment by Seifert69** [comment]
If you remove all the sun globes will the light value then be right or
wrong? I believe there's a way to get an incorrect final value.

**Comment by Seifert69** [comment]
I wonder. If you put the sub globes in a bag in your inventory. Or an open coffin on the ground

At some point value will swap to -126.

At that point is there some operation that would cause an incorrect value. E.g. if you get killed, quit. or something else. Pick one out drop it in the room, etc.

Perhaps it's related to that.

**Comment by Seifert69** [comment]
I increased light counters to 16 bits. Should be plenty. Closing issue. If a light bug appears we'll reopen.
