### ISSUE TITLE
Admin - Barbarian

### ISSUE THREAD

**Issue by Seifert69** [Seifert69/DikuMUD3#50]
New character profession (or race?). Adding a frenzy skill alongside would be nice

**Comment by Seifert69** [comment]
Chris, hope this fits into the other project you're looking at :-) Otherwise please just reject.

**Comment by chrisspanton** [comment]
It does.

For races, we already half-orc, half-ogre, and groll,. throwing barbarian in that mix doesnt seem to add value to me off the top. 

I think you're right that it should be a profession.

I could see some high con/str restrict skills that could compel someone to build to that profession, but they would need to be pretty compelling to counterbalance the loss of other abilities in favor of con.

I'll start working on laying it out.

**Comment by Seifert69** [comment]
Totally agree. It's obviously a profession :-)

**Comment by Seifert69** [comment]
Thanks for doing this. :-)
