### ISSUE TITLE
Web Client - click zone for cmd line

### ISSUE THREAD

**Issue by chrisspanton** [Seifert69/DikuMUD3#55]
I keep having an issue using the web client, where when I swap between windows I click the screen, and realize that I am not in the command line and able to type. I then have to move to the small command line box to click there to enter commands. Should be easier to enter commands, while maintaining ability to copy text from output window.

**Comment by Seifert69** [comment]
I agree it is an issue.

Here are some of the hidden features:

1) Press ESC at any time to get focus in the command line
2) Press ESC when already in the command line to erase what's already there
3) Double click the scroll-able communication window and it will show a modal popup with the text (frozen). Good for inspection or copy & past.

If you want to copy & paste from the main scroll-able window then I'm sure you've already discovered that when a city guard walks by, it messes up your area selection.

If we make a one-click in the main window, focus on the command line, then you can't copy & paste any longer - unless you use the double click trick above.

Let me know your thoughts on what would be a good overall solution please :-)

**Comment by Seifert69** [comment]
And by the way. I added code some time ago so that when you tab through your tabs, or ALT-tab to your browser, then it puts focus in the command area.

**Comment by Seifert69** [comment]
Closing. If anyone has a grand idea for the main window single / double click issue, please post & reopen.
