### ISSUE TITLE
Zone comiliation error assassin.zon:854

### ISSUE THREAD

**Issue by Thridi** [Seifert69/DikuMUD3#71]
VMC 2.0 Copyright (C) 2001 by Valhalla [Oct  2 2020]
Compiling 'assassin.zon'
<assassin.zon> @ 854: EOF in string
<assassin.zon> @ 854: Unterminated conditional
Fatal error compiling in preprocessor stage in file 'assassin.zon'.

**Comment by Seifert69** [comment]
Is that on the Git version of assassin's zone?  Or did you modify it? Any
particular setup you have?

**Comment by Thridi** [comment]
Sorry, I should have been more clear. Fresh git clone, trying to go through so I could build and run the server. No changes at all.

**Comment by Seifert69** [comment]
I can reproduce it. We've messed something up. Fix on its way.
