### ISSUE TITLE
Wall Guards  - Jurisdiction Breach?

### ISSUE THREAD

**Issue by chrisspanton** [Seifert69/DikuMUD3#76]
It appears as though the Wall Guards have breached their jurisdiction and are roaming the city of Midgaard, interfering in public safety and other issues the Cityguards should be addressing.

Inevitable conflict will emerge. Either that, or players will be unnecessarily spammed with too many wandering guards.

**Comment by Seifert69** [comment]
The guards wander routines bring them through the city (designed that
way).  If there's a whistle while they are in the city they'll answer the
call :-)

The wander stuff was broken. I fixed it. That might be why you never
noticed it in the old game

**Comment by Seifert69** [comment]
If you think there's a possible enhancement here do drop a note :)
