### ISSUE TITLE
Bug - death and comm channels

### ISSUE THREAD

**Issue by chrisspanton** [Seifert69/DikuMUD3#79]
Currently it appears that while in any stage of the death sequence you cannot utilize comm channels. It's as if they didnt exist. None of the related commands work. As soon as you respawn, it kicks back in to proper functioning. You do still recieve comms on channels you have joined when others send, but trying to use them, add or remove them, check which ones you are in, list membership, etc doesnt work.

**Comment by Seifert69** [comment]
I believe the death sequence dil, which has a very high priority, blocks
most commands. If you give me a list of commands you want to work while in
the death sequence, LMK.

**Comment by Seifert69** [comment]
It's a feature, but easily changed here in death.zon. Just drop me a list of valid commands plz. Looks like it's missing a fnpriority. I'll add that when I get your input.  

dilbegin noaction();
code
{
heartbeat:=3;
   :loop:
   wait(SFB_CMD, activator == self);

   if (activator.level < IMMORTAL_LEVEL)
   {
      act("You are dead, don't move!",
          A_ALWAYS, self.outside, null, null, TO_CHAR);
      block;
   }

   goto loop;
}
dilend

**Comment by chrisspanton** [comment]
This isn’t the issue... this dil doesn’t fire. It is definitely a bug we’ve introduced. 

Players should definitely be able to (and historically have been able to) use comm channels while dead. It’s how people ask for res, tell their clan to go kill the bastard who PK’d them, etc.

**Comment by Seifert69** [comment]
If it says "lie still you're dead" then it's blocked by this dil.

Probably before when there was no dil.priorities it wasn't an issue.

We could also mark comms as system priority

**Comment by chrisspanton** [comment]
I’ll post a log here when I have a moment. It doesn’t appear as if it’s getting blocked with a return message. It’s as if the commands don’t exist. It’s not only while moving through the death sequence, it’s also while in Valhalla with Odin. Hold tight I’ll send a log a bit later

**Comment by Seifert69** [comment]
Fixed.
