### ISSUE TITLE
Use of auto in cmdload.cpp fails to compile vme/src

### ISSUE THREAD

**Issue by rgautier** [Seifert69/DikuMUD3#8]
[rgautier@vps1 src]$ make all
cmdload.cpp: In function 'void skill_dump()':
cmdload.cpp:129:14: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
         for (auto it = vect.begin(); it != vect.end(); ++it)
              ^
cmdload.cpp:129:19: error: 'it' does not name a type
         for (auto it = vect.begin(); it != vect.end(); ++it)
                   ^
cmdload.cpp:129:38: error: expected ';' before 'it'
         for (auto it = vect.begin(); it != vect.end(); ++it)
                                      ^
cmdload.cpp:129:38: error: 'it' was not declared in this scope
make: *** [../build/./cmdload.o] Error 1

**Comment by iamnove** [comment]
Try adding -std=c++11 to your CXXFLAGS in the Makefile

**Comment by Seifert69** [comment]
I added std=c++11 to the Makefile flags. LMK if you can compile (what machine/compiler are you on?)

**Comment by rgautier** [comment]
Was able to compile... CentOS.

had one more problem with compiling with -j8 but removed it for success.
On a cheap VM with mem and CPU restrictions.

Much thanks
