### ISSUE TITLE
Immortal starvation and the eat, set, and restore commands

### ISSUE THREAD

**Issue by chrisspanton** [Seifert69/DikuMUD3#83]
Currently immortals gain the "eat" wizi command at level 200. 

In practice, they dont actually gain a command, it's simply that command.zon do_eat function, all the checks are skipped if level >= 200, and the command simply destroys the named food even if a mortal would be unable to eat it (food.objecttype!=ITEM_FOOD). It also means that the full value is not set on the immortal "eating", and thus they starve perpetually. 

At immortal level 239 the restore command is gained, which provides a function with "restore self" to set full (as well as thirst) to 115 (among other things), which means they will never starve providing a mitigation.

Another mitigation occurs at a lower level (230), when the set command is gained. This allows for manually setting the values triggered in a 'restore' command, including the opportunity to set full to 115.

The fact remains, that immortals < level 230 have no means to fill their full value, and perpetually starve. Since there is no similar modification to drink, their thirst value is less of an issue, as they can simply drink similar to mortals.

A few things come to mind here.

First, I'd advocate that we modify the do_advance function admin_level section to set full and thirst to 115. This would ensure that immortals of any level never suffer the effects of hunger and thirst, which seems perfectly appropriate. 

Next, I'd advocate that the restore command is set somewhere significantly lower than 230, where set is available. The logic here being that restore is significantly less impactful to the game than set (which has a super-set of restore) and really should likely be available to most immortals. I'd suggest level 210, though wouldn't argue 200 itself. At 210 the Wiz command/channel becomes available, which could be seen as a milestone in immortal advancement appropriate to correlate with the restore command. 

Finally, I'd advocate for including an if statement in do_eat to set full and thirst to 115, so any poor immortals between level 200 and 210 are able to mitigate their own perpetual starvation without intervention from a higher power. 

Thoughts?

**Comment by chrisspanton** [comment]
If nobody disagrees, I'll push the 3 changes I advocated for, and close this. Mostly wanted this here for awareness and tracking, feel free to suggest anything different!

**Comment by Seifert69** [comment]
All good.

I've always used eat to remove objects. Even if I load a player and fix
something, always end up eating whatever to get rid of it again :-))). In
guessing maybe purge does the same thing.
