### ISSUE TITLE
All comm channels are being wiped with each login

### ISSUE THREAD

**Issue by chrisspanton** [Seifert69/DikuMUD3#88]
Or not saved? Either way, every time you log in, you have no comm channels. This is rather annoying.

**Comment by Seifert69** [comment]
Implementation seems a bit odd IMO. Data is only stored as a stringlist in DIL. I added a recall flag. It might fix it.

If I'm really bored some day, the commands all ought to go into commands.def and it should only check for channel keywords. It might as well check in a self.info $channel extra for the channel. Would be much more robust. :-)
