### ISSUE TITLE
Bug - Exits display in rooms containing rooms

### ISSUE THREAD

**Issue by chrisspanton** [Seifert69/DikuMUD3#92]
If you are in a room which contains another room (example ct_9@cypress, bushes@cypress) that is empty other than you. (no players, objects, or mobs) with Change Exits enabled, the Exits information displays twice.

You can see this at ct_9@cypress if there are no other mobs that have wandered in, same for bushes@cypress, so long as you eat the skeleton first and nothing else has wandered in.

Fun!

**Comment by Seifert69** [comment]
I believe I have fixed it , although not 100% sure.
